file_format: "1"
id: souffle_v3_sweep
name: Souffl√© v3 Sweep
type: shield
url: https://github.com/climent/SouffleKeyboard
requires: [pro_micro]
features:
  - keys
  - display
  - encoder
siblings:
  - souffle_v3_sweep_left
  - souffle_v3_sweep_right
